---
- name: Converge
  hosts: all
  vars:
    coredns_server:
      - zone: 'example.tech:53'
        hosts:
        import: bind
        health: :8080
        rewrite: name regex (.*).vpn.example.tech gateway.example.tech
      - zone: '.:53'
        import: bind
        forward: . tls://2606:4700:4700::1111 tls://1.1.1.1
  pre_tasks:
    - name: install unzip
      package:
        name: unzip
        state: present
  roles:
    - role: arillso.coredns
