---
- name: Converge
  hosts: all
  vars:
    coredns_snippet:
      - bind:
        bind:
          - 127.0.0.1
          - 127.0.0.53
        cache: |
          {
            success 10000 1800
            denial  1000  300
          }
        errors:

    coredns_server:
      - zone: "example.tech:53"
        hosts:
          import: bind
        health: :8080
        rewrite: name regex (.*).vpn.example.tech gateway.example.tech
      - .:53:
          import: bind
          forward: . tls://2606:4700:4700::1111 tls://1.1.1.1
  roles:
    - role: arillso.coredns
