---
name: Role Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Role Release Test

    defaults:
      run:
        working-directory: arillso.coredns

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: arillso.coredns

      - name: Test Ansible with Molecule
        uses: arillso/action.molecule@0.0.1
        with:
          command: test
          working_directory: arillso.coredns

  publish:
    runs-on: ubuntu-latest

    name: Role Release Publish

    if: always()
    needs:
      - release

    steps:
      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v0.1.8
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
